
arabic = {
    'settings':'اعدادات',
    'help':'مساعدة',
    'about':'حول',
    'information':'معلومات',
    'tools':'الادوات',
    'people':'الافراد',
    'families':'العائلات',
    'regions':'المناطق',
    'general':'نظرة عامة',
    'favorite':'اضافة الى المفضلة',
    'expo_pdf':'تصدير كملف PDF',
    'title':'ناس سطيف',
    'language':'اللغة',
    'english':'english',
    'arabic':'العربية',
    'frensh':'francais',
    'file':'تغير ملف المعلومات',
    'navigation':'التنقل',
    'yes':'نعم' ,
    'no':'لا' ,
    'exit_message':r'تم تغير الملف<br>يجب الخروج من البرنامج لاستخدام الملف الجديد<br>هل تريد الخروج ?' ,
    'empty_table':'0 نتيجة ' ,
    'found_message':'تم العثور على' ,
    'yes':'نعم' ,
}